name: shilaf
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # supabase
  supabase_flutter:

  # firebase
  firebase_messaging:
  firebase_core:

  # カレンダー
  timezone:

  # データクラス
  freezed_annotation:

  # 状態管理
  flutter_riverpod:

  # 画面遷移
  go_router:

  # サインイン
  google_sign_in: ^6.2.1

  # 画像選択
  image_picker: ^1.1.2

  # UI
  google_fonts:

  # ユーティリティ
  intl:

  # 環境変数
  flutter_dotenv:

  # ログ
  logging: ^1.2.0

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  web:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # freezed
  freezed: ^2.4.1
  json_serializable: ^6.6.1
  build_runner: ^2.4.6
  
  # launcher icons
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # 環境変数ファイル
  assets:
    - .env
    - shilaf-logo.png

# flutter_launcher_icons configuration
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "shilaf-logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "shilaf-logo.png"
